submodule_paths:
  - "libs/"

mappings:
  - path_prefix: "src/test_servis"
    binary: "test_servis"
    module: "test"
    risk: "low"

  - path_prefix: "libs/ortak-moduller"
    binary: "ortak_kutuphane"
    module: "libs"
    risk: "medium"

  - path_prefix: "stringutil"
    binary: "ortak_kutuphane"
    module: "libs"
    risk: "medium"